version: '3.7'
services:
  seekafrique:
    image: javik223/seekafrique:0.0.5
    container_name: 'seekafrique_web'
    env_file:
      - webvariables.env
    ports:
      - 8085:80
  seekafrique_mongo:
      image: mvertes/alpine-mongo
      container_name: 'seekafrique_mongo'
      ports:
        - 27017:27017
      volumes:
        - seekafrique_mongo:/data/db
volumes:
  seekafrique_mongo: